name: Continuous Integration and Deployment

on: 
  push:
    branches:
       - main


env: 
  DOTNET_VERSION: '8.0.x'

jobs:
  build:
    runs-on: ubuntu-latest
    environment: Azure

    steps:
      - name: Checkout code🦄
        uses: actions/checkout@v4

      - name: Setup dotnet 8
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: ${{ env.DOTNET_VERSION }}

      - name: Restore dependencies
        run: dotnet restore API

      - name: Build App
        run: dotnet build -c Release --no-restore API/API.sln

      - name: Publish App
        run: dotnet publish -c Release -o ./out API/API.sln